location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/octomap.git
    name: octomap
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/octomap
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_rviz_plugins
    name: octomap_rviz_plugins
    rev: kinetic-devel
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/octomap_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_msgs
    name: octomap_msgs
    rev: melodic-devel
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/octomap_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/octomap_tools.git
    name: octomap_tools
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/octomap_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_server.git
    name: mrs_octomap_server
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/mrs_octomap_server
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_planner.git
    name: mrs_octomap_planner
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/mrs_octomap_planner
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_ros
    name: octomap_ros
    rev: melodic-devel
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/octomap_ros
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/octomap.git
    name: octomap
    rev: 4c9fcd313accf3f5b270eb1c17f4e24829dd2a24
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/octomap_tools.git
    name: octomap_tools
    rev: cdd1290331c198a3a1e5476cd292fecdd099aec0
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_server.git
    name: mrs_octomap_server
    rev: a9c02c805cff8581ae51317b89993057ceeba93e
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_octomap_planner.git
    name: mrs_octomap_planner
    rev: dc59c9f025f7ef1c85d8c9d19461b06546eea931
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_ros
    name: octomap_ros
    rev: ed2ee3ae2b513a25fed68fa55a635b4df9bbed91
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_rviz_plugins
    name: octomap_rviz_plugins
    rev: 09bc9ad5fb7543d67ab6293c14f681d161f0e8f0
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/OctoMap/octomap_msgs
    name: octomap_msgs
    rev: dcaaf62bd071db0fcd806a98a9101a2e470f7f6d
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
